### ISSUE TITLE
Dalamud API Version 6 Update

### ISSUE THREAD

**Issue by XxInvictus** [WesselKuipers/FCNameColor#14]
With 6.1 Dalamud has updated to API Version 6, I have checked this plugin by loading it as a Dev plugin with the updated API version and all seems to work correctly so you should just be able to update the API and Plugin version and be done with it! 👍

**Comment by WesselKuipers** [comment]
Thanks for checking! I've been busy moving so I haven't had the time yet to properly sit down and see if things are broken or not.

I'll see if I can do so in the next couple of hours 👍

**Comment by WesselKuipers** [comment]
I just released [2.0.3.0](https://github.com/WesselKuipers/FCNameColor/pull/15), it should be available soon!
