### ISSUE TITLE
Additional FCs causes crashes with invalid input.

### ISSUE THREAD

**Issue by darknite323** [WesselKuipers/FCNameColor#17]
Adding an additional FC without entering an actual lodestone address, causes the game to CTD.
From then on, trying to access the "Additional FCs" menu, causes an instant CTD.

**Comment by WesselKuipers** [comment]
Thanks for the report! I've been able to reproduce this myself and will have the fix out later today.

**Comment by WesselKuipers** [comment]
This should be fixed in 2.1.0.5, let me know if any other issues pop up!

**Comment by darknite323** [comment]
Thank you! :)
