### ISSUE TITLE
Plugin settings window isnt compatible with Scaling options

### ISSUE THREAD

**Issue by DaCyclops** [WesselKuipers/FCNameColor#19]
Since the new version, I was wondering how to add groups. There were no options.
I have now found the reason - the FCNC settings window doesn't handle scaling correctly.
I have 125% scaling on my Dalamud, and the main settings window will scale the items, but because the window itself has a fixed horizontal size, I can never see the Add/Delete buttons unless I adjust my scaling.

either the settings window should let us resize it horizontally, or it should automatically scale if the width at its widest point is larger.

(Sorry about no pictures, I am making this report the next day).

**Comment by WesselKuipers** [comment]
I've had a quick look and decided to try the auto scaling option, could you check if this is any better for you?

Custom repo URL:
https://raw.githubusercontent.com/WesselKuipers/MyDalamudPlugins/main/pluginmaster.json

**Comment by DaCyclops** [comment]
v2.1.0.6 is working much better, even with scaling.
![image](https://user-images.githubusercontent.com/13886128/166215258-54bfb5d9-1c45-45f8-80c3-d8d12c7fd062.png)
