### ISSUE TITLE
Grabbing the wrong FC

### ISSUE THREAD

**Issue by RangePup** [WesselKuipers/FCNameColor#20]
With 6.18 the plugin is coloring the wrong FC. It was the FC of a different player nearby. I thought it might have been cause I tried to DC Travel when I first noticed it, so I tried to restart the game. When I logged in, it had pulled a different nearby FC, also not mine, to highlight. I tried to change zones to see if that fixed it, but nothing changed, it was still on this second FC. I then tried to relog, going back to character select and coming back in, and then it told me I was not in an FC. At this point I had disabled and reenabled the plugin, which then fixed it. Relogged again to see if it stayed fixed, it did not. Another FC from somebody nearby. Again, disabling and reenabling fixed it.

**Comment by Arlarius** [comment]
This is been happening to me too, every time I log in it grabs a random FC nearby and counts it as mine, as well as saying as I'm not in one. Have to disable and re-enable the plugin every login.

**Comment by RangePup** [comment]
Seems to be working fine. Tried to World Visit and relog a couple times in populated areas and it seems to be highlighting mine correctly.

**Comment by WesselKuipers** [comment]
Good to hear! I've released version 3.0.0.1 outside of testing, if things break again feel free to create a new issue.
