### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by Frost212** [WesselKuipers/FCNameColor#22]
Plugin is no longer working as of Patch 6.2. Would love to see an update for it.

**Comment by WesselKuipers** [comment]
Previously I used XivCommon to hook into the nameplate updating function internally, but since that's currently not being updated, I used an alternative method.

If you enable testing plugins you should see FCNC pop up as version 3.0.0.0, can you check if this version is working for you?

**Comment by Korrigan1340** [comment]
Testing version is working for me. Thanks!!!

**Comment by WesselKuipers** [comment]
I've released 3.0.0.1 on the main branch, it should be available for everyone now. Unfortunately it won't work well with other plugins that do things with the nameplates for now, so I've also added the option to only make it work inside duties if that's what you prefer.
