### ISSUE TITLE
An option to only color inside duties?

### ISSUE THREAD

**Issue by Spanglish1337** [WesselKuipers/FCNameColor#23]
As title say, only an option to have it color FC members only inside duties?

I am using simple tweaks to have a star and golden color outside of instances and I am using FC color because it dyes the HP bar red and it's easier to see them in instances when I teach them end-game fights.

**Comment by WesselKuipers** [comment]
I like it! I'll see what I can do.

Unfortunately right now with the way the game works I can't easily make SimpleTweaks' custom FC tags work nicely with FCNC, but an option like this shouldn't be too hard.

**Comment by Spanglish1337** [comment]
> I like it! I'll see what I can do.
> 
> Unfortunately right now with the way the game works I can't easily make SimpleTweaks' custom FC tags work nicely with FCNC, but an option like this shouldn't be too hard.

Thank you!!

What was the default red color? I changed by accident and I can't remember which shade of red is the original one

**Comment by WesselKuipers** [comment]
By default it uses the one with the ID of 14

**Comment by WesselKuipers** [comment]
Looks like I forgot to actually mention it in this issue, but this has been implemented for a while now already 😅
