### ISSUE TITLE
Option to exclude friends

### ISSUE THREAD

**Issue by Kamppix** [WesselKuipers/FCNameColor#36]
If possible, an option to exclude characters on your friends list would be neat.

Currently, when the plugin is configured to color the entire nameplate, it always overrides the friend color from the game options.

**Comment by WesselKuipers** [comment]
Can do that!

What do you propose it should do when you have it set to ignore friends as well as having the entire nameplate recoloured, should it recolour only the FC tag or just do nothing at all?

**Comment by Kamppix** [comment]
Sorry for the late reply. I'd personally like if

**Comment by Kamppix** [comment]
Sorry for the late reply and accidental closing...

I'd suggest it does nothing in this scenario.

**Comment by WesselKuipers** [comment]
I included this option in 4.0.0.0, if there's an issue with this feature feel free to reopen!

**Comment by WesselKuipers** [comment]
just a heads-up, 4.0.0.0 has been temporarily taken down due to it crashing for some people, working on a fix today.
