### ISSUE TITLE
Additioan FCs window responsivness

### ISSUE THREAD

**Issue by iv230** [WesselKuipers/FCNameColor#39]
Because when you are using a lot of CL you might reach the height of you screen, this winow shoudl feature a vertical scroll and a possibility to resize
![Capture d’écran 2023-09-13 142744](https://github.com/WesselKuipers/FCNameColor/assets/17131928/cadfb7f9-a796-4c27-813b-b5d0df770832)

**Comment by WesselKuipers** [comment]
Hi, sorry for the late response. I'm currently working on the next version which involves changing the way the config is stored, but I'll definitely have a look at this as well. 

I'll add a scroll bar for it, will have to look at resizing as well.

**Comment by WesselKuipers** [comment]
This is what I ended up going with:

https://github.com/WesselKuipers/FCNameColor/assets/4731930/7885ed51-3625-4584-a686-9892ccb2715a

**Comment by WesselKuipers** [comment]
Just checking in real quick: Did everything continue working like normal after updating? I wrote some logic to transfer the old config into the new config layout, including adding your own active FC in that list.

**Comment by WesselKuipers** [comment]
just a heads-up, 4.0.0.0 has been temporarily taken down due to it crashing for some people, working on a fix today.
