### ISSUE TITLE
Something is wrong here.

### ISSUE THREAD

**Issue by LittleCupcake93** [WesselKuipers/FCNameColor#44]
When will there be an update for the Dalamud plugin? I've tried to download it, but it's disabled because of incompatibilites. If it's not an update there's needed, what's happening then?
![ffxiv_dx11_aUePhlhM8E](https://github.com/WesselKuipers/FCNameColor/assets/47774957/d5d6bf93-0f9c-4894-b26e-d38153728896)

Can you maybe help me out with this?
Thanks!

**Comment by WesselKuipers** [comment]
Version 4.0.0.0 ended up getting taken down because it was causing crashes for some people. 
I wasn't able to reproduce the crashes myself but I had a stab at it anyway and released a new testing version, version 4.0.0.1.

To enable these:
/xlsettings -> Experimental -> Get Plugin Testing Builds

**Comment by LittleCupcake93** [comment]
And how will i install that within Dalamud Plugin Installer? I started using Dalamud yesterday, so I'm not familiar with it at all and the different plugins.

**Comment by WesselKuipers** [comment]
When you type in /xlsettings and go to the Experimental tab you'll see the option to enable plugin testing builds:
![image](https://github.com/WesselKuipers/FCNameColor/assets/4731930/1c2589e9-3ab7-462c-80e8-8a304a71dd3a)

After enabling that and hitting the save button in the bottom right corner, you can go to the plugin installer and hit update plugins and it'll should get the latest test version.

Later today version 4.0.0.2 should be available as a regular non-test version also
