### ISSUE TITLE
Suggestion:  Allow more then two colors

### ISSUE THREAD

**Issue by MalicT** [WesselKuipers/FCNameColor#47]
Set it up, have my FC colored and then a  few other FCs that we also do events with, but right now because it only allows two, "Default" and "Other FC"

I tried to hit the + button thinking it would allow me to add other variations, but it does not seem to do anything.

Would like to be able to set other colors per FC

**Comment by WesselKuipers** [comment]
This is actually already possible, though maybe not entirely intuitively laid out right now.
The `Default` and `Other FC` options are different groups which you can assign FCs to, so if you want more options there you can add a new group in the main config window, which will make them show up in the dropdowns for assigning colours.

**Comment by WesselKuipers** [comment]
The + button next to the group selection in the main config window should make a new window pop up in which you can add new groups.

I'll probably move this to a separate section entirely in the future, right now it's not the most intuitive.

**Comment by MalicT** [comment]
Then I need to change what this report is about, the + button is doing nothing for me, no popup at all

**Comment by MalicT** [comment]
I found out two things.  I was pressing the + and not getting a pop up window, I had to exit to title screen before that would work. 
 It also popped up behind the main Dalamund plugin window.
 
 When I was on the title screen, the FC management window would not open if the add group window was open.

**Comment by WesselKuipers** [comment]
All of the FC management stuff is per-character so you can't really do much more than adding/removing groups and changing the global settings, not sure what's going on with the popup not showing up properly though, will have to take a look at that 👀

**Comment by WesselKuipers** [comment]
I'm trying to reproduce this on my end, and it seems to be working, even on the title screen:
https://github.com/WesselKuipers/FCNameColor/assets/4731930/2eb17416-4b8b-47e5-a9b2-51db07f3ff11

Perhaps the window is there but it's somewhere off to the side, possibly minimized too?

**Comment by WesselKuipers** [comment]
Could you try the following steps to reset the window positioning?

1. Close the game.
2. Go to `%AppData%\XIVLauncher\`.
3. Delete dalamudUI.ini.
4. Start the game.
