### ISSUE TITLE
Enabling the plugin causes screen tearing

### ISSUE THREAD

**Issue by guardian84** [WesselKuipers/FCNameColor#7]
As title, I noticed significant screen tearing when this plugin is enabled. Disabling this plugin resolves the screen tear

**Comment by guardian84** [comment]
Hey Wessel,

Thanks for the update, I will give it a go and test it for a few days. I'll
let you know the outcome :) Much appreciated!

**Comment by WesselKuipers** [comment]
It's been a while, if the issue still persists feel free to open this issue back up.
