### ISSUE TITLE
FC updating

### ISSUE THREAD

**Issue by SaintSpudders** [WesselKuipers/FCNameColor#8]
hello! just curious if there is a way to force the plugin to update the info from Lodestone. as it keeps highlighting my previous FCs members and not the one im in currently. ive uninstalled it and reinstalled it ect all that jazz. cant figure anything that might work., Thanks :D

**Comment by WesselKuipers** [comment]
Hi!

Right now there isn't a way yet to fully reset this yet outside of changing the config manually. I'll have to find a good way to allow for users to have more control over this while also not spamming Lodestone too much.

For the time being you can try either manually editing the config file or deleting the config entirely.

If you're on 2.0.0.1 (The current public build):
`%appdata%/XIVLauncher/pluginConfigs/FCNameColor.json` -> Remove the property `FcMembers` in its entirety.

If you're on 2.0.1.0 (The current test build):
`%appdata%/XIVLauncher/pluginConfigs/FCNameColor.json` -> Remove the property `PlayerFCs` in its entirety.

**Comment by WesselKuipers** [comment]
Right now there are some issues with plugins that rely on data from Lodestone since the recent Lodestone website update added additional measures against scraping, which the version in the test build is looking to fix, but it's still having issues unfortunately.

**Comment by SaintSpudders** [comment]
Ah yes deleting the config file, disabling and re-installing made it work for me! thank you so much! :D

**Comment by WesselKuipers** [comment]
Just wanted to pop in real quick and mention that version 2.0.2.0 does this on its own, so this shouldn't be an issue anymore. It's currently in testing but will be available normally soon™.
