### ISSUE TITLE
4 hrs and still fetching

### ISSUE THREAD

**Issue by DiggityMan420** [WesselKuipers/FCNameColor#9]
So its been almost 4 hrs and it still hasnt worked to load the lodestone pic [here](https://imgshare.io/image/r6NuiQ)

**Comment by WesselKuipers** [comment]
Right now it's set up so that it only tries to fetch the list of FC members once, on startup. Most of the time when it fails it's because of XIVApi getting too many requests with Lodestone rate limiting it.

Until I finish the next version you could try disabling and re-enabling the plugin until it does resolve properly (should take about 10 seconds), or you can try the testing version.

How to enable Plugin Testing:
1. Type /xlsettings in game.
2. Go to the Experimental tab
3. Click the checkbox for Get plugin testing builds
4. Save / Save and Close

**Comment by DiggityMan420** [comment]
Done and still waited 2 hrs this time nothing no change  Sent from Mail for Windows From: Wessel KuipersSent: Tuesday, November 23, 2021 6:01 PMTo: WesselKuipers/FCNameColorCc: Wasted Wanderer; AuthorSubject: Re: [WesselKuipers/FCNameColor] 4 hrs and still fetching (Issue #9) Right now it's set up so that it only tries to fetch the list of FC members once, on startup. Most of the time when it fails it's because of XIVApi getting too many requests with Lodestone rate limiting it.Until I finish the next version you could try disabling and re-enabling the plugin until it does resolve properly (should take about 10 seconds), or you can try the testing version.How to enable Plugin Testing:Type /xlsettings in game.Go to the Experimental tabClick the checkbox for Get plugin testing buildsSave / Save and Close—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DiggityMan420** [comment]
i will try from time to time but wouldnt it be easier to make it read the FC then lodestone even if u make it so open up the FC window

**Comment by DiggityMan420** [comment]
or read on targeted for the first time then save this would take the lode off the lodestone query

**Comment by DiggityMan420** [comment]
I can tell you to use this but i can point you in a direction Look at [PIC](https://imgshare.io/image/rNp6gc) works with all my FC mates i see too.
This is the [Simple Tweaks](https://github.com/Caraxi/SimpleTweaksPlugin) Plugin
 take a look [here](https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks/UiAdjustment/CustomFreeCompanyTags.cs) this doesnt sue the lodstone at all

**Comment by WesselKuipers** [comment]
The problem with the way SimpleTweaks does it, is that it relies on the FC tag. The FC tag isn't available inside duties or when you're visiting other servers so it isn't able to change the nameplates of FC members in those situations.

Another issue with it is that the tags aren't actually unique. The first version of this plugin actually did things this way as well until ran into those issues.

I'm planning on working on fixing this today using [NetStone](https://github.com/xivapi/NetStone) instead, as well as some extra controls to reset the cache and add a proper retry button.

**Comment by WesselKuipers** [comment]
Changes added in https://github.com/WesselKuipers/FCNameColor/pull/10 are currently available in version 2.0.2.0 as a testing plugin, let's see if this fixes your issues.

**Comment by WesselKuipers** [comment]
It's been a while, if the issue still persists, feel free to reopen this issue.
